version: '3.8'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - 'zookeeper_data:/confluentinc/zookeeper/data'
    networks:
      - test-network
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_KRAFT_MODE_ENABLED: "true"
      KAFKA_KRAFT_CLUSTER_ID: "kafka_cluster"
    volumes:
      - 'kafka_data:/confluentinc/kafka/data'
    networks:
      - test-network
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '3001:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY_URL=http://localhost:8081
    networks:
      - test-network
  test:
    build: .
    container_name: test
    hostname: test
    ports:
      - "3030:3030"
    networks:
      - test-network
    depends_on:
      - kafka-ui
networks:
  test-network:
volumes:
  zookeeper_data:
  kafka_data:
